### ISSUE TITLE
Cannot find module 'babel-runtime/regenerator'

### ISSUE THREAD

**Issue by heartz66** [NebulousLabs/Nodejs-Sia#49]
I have followed the instructions but when I try to run the code I am getting the following error:
`
Error: Cannot find module 'babel-runtime/regenerator'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/stan/Desktop/image-hosting/node_modules/sia.js/lib/sia.js:8:20)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
`

**Comment by snehap007** [comment]
I am getting the same issue please help me in this.
